### ISSUE TITLE
JSON dependency clashes with Puppet 5

### ISSUE THREAD

**Issue by dploeger** [bstopp/crx_packmgr_api_client#2]
The JSON library dependency (1.8) clashes with Puppet's Ruby bundling, which only supports the JSON library in version 2.0.

We tried the package with an updated dependency on our site and it works.

**Comment by zipkid** [comment]
+1

**Comment by wimsymons** [comment]
Hi @bstopp, just backing my colleague @zipkid here. This change is absolutely needed for us to upgrade to Puppet 5. Can we get this merged as soon as possible? That would be great!

**Comment by bstopp** [comment]
Fixed in v1.3.0
